version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:6.8.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:6.8.13
    container_name: logstash
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ${PWD}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${PWD}/logs:/logs

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.8.13
    container_name: filebeat
    user: root
    volumes:
      - ${PWD}/logs:/var/lib/docker/containers/logs:ro
      - ${PWD}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

  kibana:
    image: kibana:6.8.13
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch